CC=clang
CFLAGS=-g -fblocks -Weverything -Wno-padded -Werror -Wno-format-nonliteral
RECORDS_DATASET=/Users/esposito/ownCloud/LabAlgoritmi/ASD2015-16/Laboratorio/DatasetsGenerators/records/records.csv
DIST_DATASET=/Users/esposito/ownCloud/LabAlgoritmi/ASD2015-16/Laboratorio/DatasetsGenerators/cities/italian_dist_graph.csv
# linux
#LDFLAGS=-lBlocksRuntime
#LIBTOOL=ar r

# OS X
LDFLAGS=
LIBTOOL=libtool -static -o
